version: '3'
services:
  web:
    build: ./nginx
    ports:
      - '8080:80'
    links:
      - php-fpm
    volumes:
      - ./data:/usr/share/nginx/html
  php-fpm:
    build: ./php-fpm
    links:
      - db
    volumes:
      - ./data:/usr/share/nginx/html
  db:
    build: ./mysql
    container_name: mysql_host
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
       MYSQL_ROOT_PASSWORD: rootpass
       MYSQL_USER: user
       MYSQL_PASSWORD: userpass
       MYSQL_DATABASE: sample
       TZ: 'Asia/Tokyo'
  
  phpmyadmin:
    container_name: test_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOSTS=mysql_host
    - PMA_USER=root
    - PMA_PASSWORD=rootpass
    ports:
    - 8000:80

